### ISSUE TITLE
Tree.read(): expected 'end-of-string' but got '(S'  at index 486.

### ISSUE THREAD

**Issue by firdiar** [famrashel/idn-treebank#2]
I asume it is typo at line 263, because there's multiple S in sequence

im using python with library

`from nltk import Tree`

![image](https://user-images.githubusercontent.com/33082025/77286770-8cf02080-6d06-11ea-9593-8069ba14f660.png)

**Comment by famrashel** [comment]
Do you mean this line?

`263	(S    (NP-SBJ    (PRP	    (Dia))) (ADVP  (RB	    (juga))) (VP    (VB	    (mengatakan)) (Z	    (,)) (SBAR  (0) (S    (SBAR    (SC	    (meski)) (S    (PP    (IN	    (pada)) (NP    (CD	    (22)) (NNP	    (Maret)))) (NP-SBJ    (NNP	    (LPS))) (VP    (MD    (mulai)) (VP    (VB	    (memberlakukan)) (NP    (NP    (NN	    (batas)) (NN	    (simpanan))) (SBAR    (SC	    (yang)) (S    (NP-SBJ-1  (*)) (VP    (VB	    (dijamin)) (NP  (*-1)))))) (NP    (QP    (JJ	    (sebesar)) (SYM	    (Rp)) (CD	    (100)) (CD	    (juta))) (*U*)))))) (Z	    (,)) (NP-SBJ    (NP  (NP    (NP    (NN	    (tingkat)) (NN	    (kepercayaan))) (NP    (FW	    (level)) (FW	    (of)) (FW	    (confidence)))) (NP  (NN	    (masyarakat)))) (PP    (IN	    (terhadap)) (NP    (NN	    (perbankan))))) (VP    (MD	    (masih)) (ADJP    (RB	    (tetap)) (JJ	    (tinggi))))))) (Z	    (.)))`

I think there is nothing strange in this line. It is possible to have multiple _S_ tags inside one big tree when using _SBAR_ tag.

**Comment by wisn** [comment]
@firdiar I believe there is nothing strange about that line. However, since NLTK can't read it you can just remove that one line then try to parse once again.

**Comment by famrashel** [comment]
I will close the issue as there seems to be no problem with the dataset itself
